development:
  adapter: postgresql
  encoding: unicode
  database: sunny_development
  pool: 5
  username: kim
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: sunny_development
  pool: 5
  username: kim
  password: 